version: '3.7'

services:
  webservice:
    build: .
    image: webservice
    container_name: webservice
    ports:
      - '5004:5000'
    command: python manage.py
    volumes:
      - .:/usr/src/app/webservice
    environment:
      - db_driver=ODBC Driver 17 for SQL Server
      - db_server=hobbies-mdc.database.windows.net
      - db_port=1433
      - db_database=bks
      - db_username=bks
      - admin_email=admin@admin.com
    secrets:
      - db_pwd
      - flask_secret_key
    # Environment vars to set: APP_SETTINGS, DB_URL, FLASK_SECRET_KEY, db_schema