version: '3.7'

services:
  webservice:
    build: .
    image: webservice
    container_name: webservice
    ports:
      - '5004:5000'
    command: python manage.py
    volumes:
      - .:/usr/src/app/webservice
    environment:
      - admin_username=admin
    secrets:
      - db_pwd
      - flask_secret_key
      - admin_pwd
      - user_pwd